In [1]:
from pathlib import Path
import sys
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

sys.path.append(str(Path().resolve().parent))
from src.data_processing.data_processing_copy import make_data_from_faculty, clean_data, make_data_from_program, make_features, process_data
from src.data_processing.data_processing_copy import main as main_data

In [2]:
df_clean = main_data()

In [3]:
df_clean

,student_id_hash,3_1_Дисциплина: Безопасность жизнедеятельности,3_1_Дисциплина: Специальные технологии,3_2_Дисциплина: История России,3_2_Дисциплина: История и теория дизайна. Базовый курс,3_2_Дисциплина: История классического искусства,3_2_Дисциплина: Основы российской государственности,3_2_Дисциплина: Специальные технологии,3_2_Дисциплина: Цифровая грамотность,3_3_Дисциплина: Независимый экзамен по цифровой грамотности,...,3_4_Дисциплина: История России,3_4_Дисциплина: История и теория дизайна. Базовый курс,3_4_Дисциплина: История и теория дизайна. Современное искусство,3_4_Дисциплина: Независимый экзамен по программированию. Начальный уровень,3_4_Дисциплина: Правовая грамотность,3_4_Дисциплина: Специальные технологии,3_4_Дисциплина: Экономика,student_status,place_type,program
0,0042afc4255d18e37391b845aa044e04,10.0,7.0,9.0,8.0,9.000000,10.0,7.0,6.0,5.5,...,9.0,9.0,7.0,7.5,9.0,7.0,9.0,study,Коммерческие,Дизайн
1,010ef16727dd7234de23f0e7b2a766ec,6.0,5.0,7.0,8.0,9.000000,9.0,6.0,7.5,9.0,...,8.0,7.0,7.0,9.0,9.0,6.0,9.0,study,По межправительственным соглашениям,Дизайн
2,0131b19e4c1c79fbc24520da47dc906d,9.0,8.0,9.0,9.0,9.000000,9.0,8.0,6.0,6.0,...,9.0,9.0,7.0,10.0,8.0,6.0,8.0,study,Коммерческие,Дизайн
3,01bc461e2eadb63e263cce89469a4875,8.0,9.0,7.0,8.0,9.000000,10.0,8.0,7.0,8.0,...,6.0,8.0,8.0,6.0,6.0,8.0,9.0,study,По межправительственным соглашениям,Дизайн
4,01ef5e82684dc6a7e20fef7e3c2c96ec,9.0,10.0,9.0,9.0,10.000000,9.0,10.0,7.5,8.0,...,8.0,10.0,9.0,10.0,9.0,9.0,8.0,study,Бюджетные,Дизайн
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,fd3cd211ccdb941efcda0fa2b591a51f,5.0,6.0,7.0,7.0,4.666667,10.0,6.0,3.5,4.0,...,5.0,7.0,7.0,5.0,9.0,7.0,6.0,study,Целевые,Дизайн
478,fd936b53d240f46ea4dbffe0c8869bc3,8.0,8.0,7.0,8.0,3.500000,9.0,6.0,5.5,6.0,...,7.0,8.0,7.0,4.5,8.0,7.0,7.0,study,Коммерческие,Дизайн
479,fdca69e3191498ab3e1b1399b79549d1,9.0,10.0,9.0,9.0,9.000000,10.0,10.0,8.0,10.0,...,9.0,9.0,7.0,7.0,5.0,9.0,8.0,study,Коммерческие,Дизайн
480,fe762a3f9971e45bec6402b9e79228ba,9.0,9.0,7.0,9.0,6.000000,9.0,9.0,6.5,7.0,...,8.0,9.0,8.0,8.0,7.0,9.0,8.0,study,Коммерческие,Дизайн
481,ffe4018d7d2fbcefa4e7ab1d9e52d670,9.0,7.0,4.0,9.0,8.000000,10.0,9.0,7.0,8.0,...,6.0,8.0,7.0,5.0,8.0,8.0,8.0,study,Коммерческие,Дизайн

In [4]:
df_clean.drop(columns=['program'])

,student_id_hash,3_1_Дисциплина: Безопасность жизнедеятельности,3_1_Дисциплина: Специальные технологии,3_2_Дисциплина: История России,3_2_Дисциплина: История и теория дизайна. Базовый курс,3_2_Дисциплина: История классического искусства,3_2_Дисциплина: Основы российской государственности,3_2_Дисциплина: Специальные технологии,3_2_Дисциплина: Цифровая грамотность,3_3_Дисциплина: Независимый экзамен по цифровой грамотности,...,3_4_Дисциплина: Внутренний экзамен по английскому языку (1 курс),3_4_Дисциплина: История России,3_4_Дисциплина: История и теория дизайна. Базовый курс,3_4_Дисциплина: История и теория дизайна. Современное искусство,3_4_Дисциплина: Независимый экзамен по программированию. Начальный уровень,3_4_Дисциплина: Правовая грамотность,3_4_Дисциплина: Специальные технологии,3_4_Дисциплина: Экономика,student_status,place_type
0,0042afc4255d18e37391b845aa044e04,10.0,7.0,9.0,8.0,9.000000,10.0,7.0,6.0,5.5,...,7.0,9.0,9.0,7.0,7.5,9.0,7.0,9.0,study,Коммерческие
1,010ef16727dd7234de23f0e7b2a766ec,6.0,5.0,7.0,8.0,9.000000,9.0,6.0,7.5,9.0,...,3.0,8.0,7.0,7.0,9.0,9.0,6.0,9.0,study,По межправительственным соглашениям
2,0131b19e4c1c79fbc24520da47dc906d,9.0,8.0,9.0,9.0,9.000000,9.0,8.0,6.0,6.0,...,4.0,9.0,9.0,7.0,10.0,8.0,6.0,8.0,study,Коммерческие
3,01bc461e2eadb63e263cce89469a4875,8.0,9.0,7.0,8.0,9.000000,10.0,8.0,7.0,8.0,...,4.0,6.0,8.0,8.0,6.0,6.0,8.0,9.0,study,По межправительственным соглашениям
4,01ef5e82684dc6a7e20fef7e3c2c96ec,9.0,10.0,9.0,9.0,10.000000,9.0,10.0,7.5,8.0,...,6.0,8.0,10.0,9.0,10.0,9.0,9.0,8.0,study,Бюджетные
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,fd3cd211ccdb941efcda0fa2b591a51f,5.0,6.0,7.0,7.0,4.666667,10.0,6.0,3.5,4.0,...,6.0,5.0,7.0,7.0,5.0,9.0,7.0,6.0,study,Целевые
478,fd936b53d240f46ea4dbffe0c8869bc3,8.0,8.0,7.0,8.0,3.500000,9.0,6.0,5.5,6.0,...,6.0,7.0,8.0,7.0,4.5,8.0,7.0,7.0,study,Коммерческие
479,fdca69e3191498ab3e1b1399b79549d1,9.0,10.0,9.0,9.0,9.000000,10.0,10.0,8.0,10.0,...,6.0,9.0,9.0,7.0,7.0,5.0,9.0,8.0,study,Коммерческие
480,fe762a3f9971e45bec6402b9e79228ba,9.0,9.0,7.0,9.0,6.000000,9.0,9.0,6.5,7.0,...,8.0,8.0,9.0,8.0,8.0,7.0,9.0,8.0,study,Коммерческие
481,ffe4018d7d2fbcefa4e7ab1d9e52d670,9.0,7.0,4.0,9.0,8.000000,10.0,9.0,7.0,8.0,...,4.0,6.0,8.0,7.0,5.0,8.0,8.0,8.0,study,Коммерческие

In [5]:
def str_to_int_stadent_status (df : pd.DataFrame):
    df["student_status"] = df["student_status"].map({
        "study": 0,
        "graduated": 0,
        "expelled": 1,
        "leave" :  1
    })
    return df
df_clean = str_to_int_stadent_status(df_clean)

In [6]:


categorical_cols = ['place_type']

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_array = encoder.fit_transform(df_clean[categorical_cols])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_cols)
)

In [7]:
df_final = pd.concat([df_clean.drop(columns=categorical_cols), encoded_df], axis=1)
df_final

,student_id_hash,3_1_Дисциплина: Безопасность жизнедеятельности,3_1_Дисциплина: Специальные технологии,3_2_Дисциплина: История России,3_2_Дисциплина: История и теория дизайна. Базовый курс,3_2_Дисциплина: История классического искусства,3_2_Дисциплина: Основы российской государственности,3_2_Дисциплина: Специальные технологии,3_2_Дисциплина: Цифровая грамотность,3_3_Дисциплина: Независимый экзамен по цифровой грамотности,...,3_4_Дисциплина: Специальные технологии,3_4_Дисциплина: Экономика,student_status,program,place_type_Бюджетные,place_type_Коммерческие,place_type_Коммерческие за счет средств вуза,place_type_Коммерческие места для иностранных граждан,place_type_По межправительственным соглашениям,place_type_Целевые
0,0042afc4255d18e37391b845aa044e04,10.0,7.0,9.0,8.0,9.000000,10.0,7.0,6.0,5.5,...,7.0,9.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0
1,010ef16727dd7234de23f0e7b2a766ec,6.0,5.0,7.0,8.0,9.000000,9.0,6.0,7.5,9.0,...,6.0,9.0,0,Дизайн,0.0,0.0,0.0,0.0,1.0,0.0
2,0131b19e4c1c79fbc24520da47dc906d,9.0,8.0,9.0,9.0,9.000000,9.0,8.0,6.0,6.0,...,6.0,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0
3,01bc461e2eadb63e263cce89469a4875,8.0,9.0,7.0,8.0,9.000000,10.0,8.0,7.0,8.0,...,8.0,9.0,0,Дизайн,0.0,0.0,0.0,0.0,1.0,0.0
4,01ef5e82684dc6a7e20fef7e3c2c96ec,9.0,10.0,9.0,9.0,10.000000,9.0,10.0,7.5,8.0,...,9.0,8.0,0,Дизайн,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,fd3cd211ccdb941efcda0fa2b591a51f,5.0,6.0,7.0,7.0,4.666667,10.0,6.0,3.5,4.0,...,7.0,6.0,0,Дизайн,0.0,0.0,0.0,0.0,0.0,1.0
478,fd936b53d240f46ea4dbffe0c8869bc3,8.0,8.0,7.0,8.0,3.500000,9.0,6.0,5.5,6.0,...,7.0,7.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0
479,fdca69e3191498ab3e1b1399b79549d1,9.0,10.0,9.0,9.0,9.000000,10.0,10.0,8.0,10.0,...,9.0,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0
480,fe762a3f9971e45bec6402b9e79228ba,9.0,9.0,7.0,9.0,6.000000,9.0,9.0,6.5,7.0,...,9.0,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0
481,ffe4018d7d2fbcefa4e7ab1d9e52d670,9.0,7.0,4.0,9.0,8.000000,10.0,9.0,7.0,8.0,...,8.0,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 29 columns):
 #   Column                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                 --------------  -----
 0   student_id_hash                                                                                        482 non-null    str
 1   3_1_Дисциплина: Безопасность жизнедеятельности                                                         482 non-null    float64
 2   3_1_Дисциплина: Специальные технологии                                                                 482 non-null    float64
 3   3_2_Дисциплина: История России                                                                         482 non-null    float64
 4   3_2_Дисциплина: История и теория дизайна. Базовый курс                                                 482 non-null    float64
 5   3_2_Дисциплина: История классического искусства                                                        482 non-null    float64
 6   3_2_Дисциплина: Основы российской государственности                                                    482 non-null    float64
 7   3_2_Дисциплина: Специальные технологии                                                                 482 non-null    float64
 8   3_2_Дисциплина: Цифровая грамотность                                                                   482 non-null    float64
 9   3_3_Дисциплина: Независимый экзамен по цифровой грамотности                                            482 non-null    float64
 10  3_3_Дисциплина: Основы программирования на языке Python                                                482 non-null    float64
 11  3_3_Дисциплина: Прикладное применение генеративных нейросетей в креативных индустриях и промпт-дизайн  482 non-null    float64
 12  3_3_Дисциплина: Специальные технологии                                                                 482 non-null    float64
 13  3_4_Дисциплина: Внутренний экзамен по английскому языку (1 курс)                                       482 non-null    float64
 14  3_4_Дисциплина: История России                                                                         482 non-null    float64
 15  3_4_Дисциплина: История и теория дизайна. Базовый курс                                                 482 non-null    float64
 16  3_4_Дисциплина: История и теория дизайна. Современное искусство                                        482 non-null    float64
 17  3_4_Дисциплина: Независимый экзамен по программированию. Начальный уровень                             482 non-null    float64
 18  3_4_Дисциплина: Правовая грамотность                                                                   482 non-null    float64
 19  3_4_Дисциплина: Специальные технологии                                                                 482 non-null    float64
 20  3_4_Дисциплина: Экономика                                                                              482 non-null    float64
 21  student_status                                                                                         482 non-null    int64
 22  program                                                                                                482 non-null    str
 23  place_type_Бюджетные                                                                                   482 non-null    float64
 24  place_type_Коммерческие                                                                                482 non-null    float64
 25  place_type_Коммерческие за счет средств вуза                                                           482 non-null    float64
 26  place_type_Коммерческие места для иностранных граждан                                                  482 non-null    float64
 27  place_type_По межправительственным соглашениям                                                         482 non-null    float64
 28  place_type_Целевые                                                                                     482 non-null    float64
dtypes: float64(26), int64(1), str(2)
memory usage: 109.3 KB

In [10]:
df_final['avr_4_grade'] = df_final.filter(like='3_4_Дисциплина:').mean(axis=1)
df_final.drop(columns=df_final.filter(like='3_4_Дисциплина:'))

,student_id_hash,3_1_Дисциплина: Безопасность жизнедеятельности,3_1_Дисциплина: Специальные технологии,3_2_Дисциплина: История России,3_2_Дисциплина: История и теория дизайна. Базовый курс,3_2_Дисциплина: История классического искусства,3_2_Дисциплина: Основы российской государственности,3_2_Дисциплина: Специальные технологии,3_2_Дисциплина: Цифровая грамотность,3_3_Дисциплина: Независимый экзамен по цифровой грамотности,...,3_3_Дисциплина: Специальные технологии,student_status,program,place_type_Бюджетные,place_type_Коммерческие,place_type_Коммерческие за счет средств вуза,place_type_Коммерческие места для иностранных граждан,place_type_По межправительственным соглашениям,place_type_Целевые,avr_4_grade
0,0042afc4255d18e37391b845aa044e04,10.0,7.0,9.0,8.0,9.000000,10.0,7.0,6.0,5.5,...,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,8.0625
1,010ef16727dd7234de23f0e7b2a766ec,6.0,5.0,7.0,8.0,9.000000,9.0,6.0,7.5,9.0,...,6.0,0,Дизайн,0.0,0.0,0.0,0.0,1.0,0.0,7.2500
2,0131b19e4c1c79fbc24520da47dc906d,9.0,8.0,9.0,9.0,9.000000,9.0,8.0,6.0,6.0,...,7.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,7.6250
3,01bc461e2eadb63e263cce89469a4875,8.0,9.0,7.0,8.0,9.000000,10.0,8.0,7.0,8.0,...,7.0,0,Дизайн,0.0,0.0,0.0,0.0,1.0,0.0,6.8750
4,01ef5e82684dc6a7e20fef7e3c2c96ec,9.0,10.0,9.0,9.0,10.000000,9.0,10.0,7.5,8.0,...,9.0,0,Дизайн,1.0,0.0,0.0,0.0,0.0,0.0,8.6250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,fd3cd211ccdb941efcda0fa2b591a51f,5.0,6.0,7.0,7.0,4.666667,10.0,6.0,3.5,4.0,...,6.0,0,Дизайн,0.0,0.0,0.0,0.0,0.0,1.0,6.5000
478,fd936b53d240f46ea4dbffe0c8869bc3,8.0,8.0,7.0,8.0,3.500000,9.0,6.0,5.5,6.0,...,7.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,6.8125
479,fdca69e3191498ab3e1b1399b79549d1,9.0,10.0,9.0,9.0,9.000000,10.0,10.0,8.0,10.0,...,7.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,7.5000
480,fe762a3f9971e45bec6402b9e79228ba,9.0,9.0,7.0,9.0,6.000000,9.0,9.0,6.5,7.0,...,8.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,8.1250
481,ffe4018d7d2fbcefa4e7ab1d9e52d670,9.0,7.0,4.0,9.0,8.000000,10.0,9.0,7.0,8.0,...,9.0,0,Дизайн,0.0,1.0,0.0,0.0,0.0,0.0,6.7500

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X = df_final.drop(columns=['student_id_hash', 'program'])
y = df_final['avr_4_grade']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)


model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print (mean_absolute_error(y_test, y_pred))

# print(precision_score(y_test, y_pred))

1.4915272082550378e-15